import { TestReport, User } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@example.gov',
    role: 'Admin',
    avatarUrl: 'https://i.pravatar.cc/150?u=admin@example.gov',
  },
  {
    id: '2',
    name: 'Data Entry User',
    email: 'data@example.gov',
    role: 'Data Entry User',
    avatarUrl: 'https://i.pravatar.cc/150?u=data@example.gov',
  },
];

export const testReports: TestReport[] = [
  {
    id: '1',
    uin: 'REI-BNU-2025-0001',
    applicantName: 'John Doe',
    shortAddress: 'House 1, Street 1',
    district: 'Bannu',
    category: 'Domestic',
    sanctionedLoad: '5 kW',
    proposedTransformer: 'No',
    governmentFee: 1500,
    challan: '12345 / 2025-01-10',
    electricalContractorName: 'Reliable Electrics',
    remarks: 'Standard installation.',
    entryDate: new Date('2025-01-15'),
    enteredBy: 'data@example.gov',
  },
  {
    id: '2',
    uin: 'REI-BNU-2025-0002',
    applicantName: 'Jane Smith',
    shortAddress: 'Shop 2, Market Road',
    district: 'Bannu',
    category: 'Commercial',
    sanctionedLoad: '25 kVA',
    proposedTransformer: 'Yes',
    governmentFee: 5000,
    challan: '12346 / 2025-01-11',
    electricalContractorName: 'Power Solutions',
    remarks: 'New transformer installed.',
    entryDate: new Date('2025-01-16'),
    enteredBy: 'data@example.gov',
  },
  {
    id: '3',
    uin: 'REI-BNU-2025-0003',
    applicantName: 'Bannu Industries',
    shortAddress: 'Industrial Estate',
    district: 'Bannu',
    category: 'Industrial',
    sanctionedLoad: '150 kVA',
    proposedTransformer: 'Yes',
    governmentFee: 25000,
    challan: '12347 / 2025-01-12',
    electricalContractorName: 'Power Solutions',
    remarks: 'Heavy machinery load.',
    entryDate: new Date('2025-01-17'),
    enteredBy: 'admin@example.gov',
  },
    {
    id: '4',
    uin: 'REI-LKI-2025-0001',
    applicantName: 'Lakki Marwat Mills',
    shortAddress: 'Main Road',
    district: 'Lakki Marwat',
    category: 'Industrial',
    sanctionedLoad: '200 kVA',
    proposedTransformer: 'Yes',
    governmentFee: 30000,
    challan: '12348 / 2025-01-18',
    electricalContractorName: 'Industrial Electrics',
    remarks: 'High capacity connection.',
    entryDate: new Date('2025-01-20'),
    enteredBy: 'admin@example.gov',
  },
    {
    id: '5',
    uin: 'REI-BNU-2025-0004',
    applicantName: 'Ali Khan',
    shortAddress: 'Phase 2',
    district: 'Bannu',
    category: 'Domestic',
    sanctionedLoad: '7 kW',
    proposedTransformer: 'No',
    governmentFee: 2000,
    challan: '12349 / 2025-01-19',
    electricalContractorName: 'Reliable Electrics',
    remarks: 'Approved.',
    entryDate: new Date('2025-01-21'),
    enteredBy: 'data@example.gov',
  }
];
